---
deployment:
  tasks:
    - export DEPLOYPATH=/home/medtravelcom/public_html
    - /bin/rsync -av --delete \
        --exclude='.git/' \
        --exclude='.cpanel.yml' \
        --exclude='.env' \
        --exclude='admin/logs/' \
        --exclude='logs/' \
        --exclude='tmp/' \
        --exclude='cache/' \
        --exclude='admin/uploads/' \
        --exclude='uploads/' \
        --exclude='assets/uploads/' \
        --exclude='img/uploads/' \
        --exclude='img/surgeon/uploads/' \
        ./ $DEPLOYPATH/
